# requires docker-compose 1.28.0+
version: '3.9'
services:
  lolminer-amd:
    build:
      context: .
      dockerfile: Dockerfile
    image: compscidr/lolminer:amd-dev
    container_name: lolminer
    devices:
      - /dev/dri:/dev/dri
    entrypoint: /lolminer/lolMiner --algo NEXA --pool pool.us.woolypooly.com --port 3124 --user <ADDRESS> --apihost 0.0.0.0 --apiport 4069
    profiles: ["amd"]
  lolminer-nvidia:
    build:
      context: .
      dockerfile: Dockerfile
    image: nvidia/cuda:10.2-base
    container_name: lolminer
    profiles: ["nvidia"]
    entrypoint: /lolminer/lolMiner --algo NEXA --pool pool.us.woolypooly.com --port 3124 --user <ADDRESS> --apihost 0.0.0.0 --apiport 4069
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 4
              capabilities: [gpu]
